Fix tooltip merged
logrhythm/kbn_network pull request #8
Opened 2020-02-11 23:39 UTC by craig-cogdill

2020-02-12 21:58 UTC, mejarrett commented on public/network_vis_controller.js
> +        let primaryNodeTermName, secondaryNodeTermName, edgeSizeTermName, nodeSizeTermName
Could you add a comment here that's just like `// variables for tool tip names` or something?

2020-02-12 22:24 UTC, mejarrett requested changes
Discussed IRL that we're still seeing `undefined: 0.1` on some edges (but not all!)

2020-02-12 23:41 UTC, craig-cogdill commented
The `undefined: 0.1` bug has now been fixed I believe. This were being displayed on edges between two primary nodes, as opposed to primary-secondary.

2020-02-13 22:33 UTC, mejarrett approved these changes

2020-02-13 23:40 UTC, merged